### PR TITLE
Add Alpine and Manpage

### PR DESCRIPTION
**Pull request by LeapofAzzam-backup**

### CODE REVIEW

**Comment by WMCB-Tech** [comment]
I'll add an staging branch to rlchroot

Alpine linux will be added as soon as i add Arch Linux

I'll keep this PR open until i decided to merged

**Comment by LeapofAzzam-backup** [comment]
I just fix the rlc-create at that time

**Comment by WMCB-Tech** [comment]
Ok, I'll add this to 1.05 release (bug fixes are working on rn)

And I'll add when user invokes `--help` command in case they need to use that option

I'll merge this PR as soon everything is settled, and is ready for public use (possibly YT Demo, and post it on Subreddit)

**Comment by LeapofAzzam-backup** [comment]
Could you merge it

**Comment by WMCB-Tech** [comment]
I already created a experimental-1 branch so I'll merge it there,

**Comment by WMCB-Tech** [comment]
Done, added in experimental-1 branch, I'll setup a build artifact for that version, although i don't have time to do that

**Comment by WMCB-Tech** [comment]
Only issue is alpine url isn't exist, anyway that can be fixed soon

**Comment by LeapofAzzam-backup** [comment]
I fixed it. Its actually missing "check_arch". You could push it from my fork

**Comment by WMCB-Tech** [comment]
Ok, I'll push it on the experimental branch shortly,

**Pull request merged**
